### ISSUE TITLE
Live codedoc code demo

### ISSUE THREAD

**Issue by bender2k14** [CONNECT-platform/codedoc#26]
Codedoc's code blocks are largely based on Marked (c.f. #25), but there are some differences (achieved via preprocessing).

Just like it is possible to [demo Marked](https://marked.js.org/demo/?text=*%20a%0A%60%60%60gdscript%0Ab%0A%0A%23%20comment%0Ac%0A%60%60%60%0A&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=master), is there a page where it is possible to demo codedoc's code blocks?

**Comment by loreanvictor** [comment]
Perhaps it would be possible, but definitely not as trivial:

- you can have custom components, so you would either have to drop support for custom components on such a demo page, or be able to re-bundle client-side code.
- you would also need to be able to try out custom components I suppose?
- a lot of behavior of CODEDOC's own components are shipped via client-side scripts, which would need to be properly re-applied when the source markdown changes.

anyways I suspect this issue is perhaps more related to [this repository](https://github.com/CONNECT-platform/marked), though generally it would be a nice thing to have such a demo page (at least with the standard set of components) for CODEDOC specifically.

**Comment by bender2k14** [comment]
Yes.  This is definitely a "nice-to-have" tool.  As I think you implied somewhat there, this is useful even if it doesn't support all the features possible when used in the complete environment of a user's website.

**Comment by loreanvictor** [comment]
on further thought, I would think this is best implemented as a stand-alone project. CODEDOC might need to export/expose more of its internal machinery for such a project to work nicely, but I do not think this should be part of CODEDOC core itself (separation of concerns).

as a result, I am closing this issue, though this is definitely a nice idea that should be implemented independently.
