### ISSUE TITLE
Smooth loading doesn't properly replace container body

### ISSUE THREAD

**Issue by bender2k14** [CONNECT-platform/codedoc#34]
This is spin off of https://github.com/CONNECT-platform/codedoc/issues/30#issuecomment-648110402

> > If I directly open my [sample blog post](https://tysonwilliams.coding.blog/sample-blog-post), then the comments are displayed.  But if I first open my [home page](https://tysonwilliams.coding.blog/) and then navigate to the sample blog post, the comments are not displayed.  A workaround is to refresh the page.
> 
> This is a bug with [smooth loading mechanism of CODEDOC](https://github.com/CONNECT-platform/codedoc/blob/892b19aa8a264f352367677c2c5f34b2db835051/src/transport/smooth-loading.ts#L39). Subsequent pages are loaded in the background and then the content (and other important parts) are replaced, to create a smooth and fast navigation experience. However, the container body is not replaced properly right now, which means scripts inside subsequently loaded containers are not executed normally. Inline scripts are manually executed, but right now there is no solution for remote scripts.

**Comment by loreanvictor** [comment]
I suspect replacing [`container`](https://github.com/CONNECT-platform/codedoc/blob/892b19aa8a264f352367677c2c5f34b2db835051/src/transport/smooth-loading.ts#L10) after each loading instead of [just replacing its `innerHTML`](https://github.com/CONNECT-platform/codedoc/blob/892b19aa8a264f352367677c2c5f34b2db835051/src/transport/smooth-loading.ts#L38) would fix the issue, which would also make [this](https://github.com/CONNECT-platform/codedoc/blob/892b19aa8a264f352367677c2c5f34b2db835051/src/transport/smooth-loading.ts#L39) obsolete. This should also be faster in terms of performance, though it would require proper testing to ensure nothing breaks as a result of this change.

**Comment by loreanvictor** [comment]
deployed via `@codedoc/core@0.2.6`
