### ISSUE TITLE
How to delete files after build

### ISSUE THREAD

**Issue by bender2k14** [CONNECT-platform/codedoc#37]
I want to group my posts into a folder in my repository but have them accessible via URLs that do not contain "posts/".

Here is my attempt.
```ts
afterBuild: [
  function moveUpHtmlInPosts(build: Build<CodedocConfig>) {
    files('.')
      .pick(file => file.path.startsWith("dist\\posts\\"))
      .pipe(readFile(),
            mapPath(path => path.replace("dist\\posts\\", "dist\\")),
            writeFile())
      .process();
    files('.')
      .pick(file => file.path.startsWith("dist\\posts\\"))
      .pipe(deleteFile())
      .process();
  }
],
```

I got halfway there.  The first part copies the generated HTML of the posts up one directory but second part doesn't delete any files...because `deleteFile` doesn't exist.

![2020-06-24_08-35-36_144](https://user-images.githubusercontent.com/34664007/85566610-ced67e80-b5f5-11ea-9617-149805a4f967.png)

Since `rxline/fs` exported `readFile` and `writeFile`, I was hoping that it also exported `deleteFile`, but it does not.

How can I delete the files in `dist/posts`?

P.S.
Is this a good approach to move the HTML from `dist/posts` to `dist`?

**Comment by loreanvictor** [comment]
yeah rxline doesn't have any utilities for deleting files. but I suspect you could use something [`fs.unlink()`](https://nodejs.org/api/fs.html#fs_fs_unlink_path_callback) or some other Node API.

I would simply configure my destination folder instead of manually moving the generated HTML files. This might interfere with subsequent plugins (as they would expect generated files to be where the config specifies), or other post-processors (for example `coding.blog` will override your configuration and direct generated HTML into a temporary folder, and this might mix up either with your after build hook or the other way around).

p.s. you do not need to load generated HTML files again, you can access them via `build.built`.

**Comment by bender2k14** [comment]
> I would simply configure my destination folder instead of manually moving the generated HTML files.

I know how to apply the [same configuration to all files](https://codedoc.cc/docs/config/output#html-files).  As the documentation says, the configuration...
```
  dest: {
    html: 'dist/html',
  },
```

...will map this input...
```
docs/md/index.md
docs/md/whatever/stuff.md
```

...to this output...
```
dist/html/index.html
dist/html/whatever/stuff.html
```

...but I want to map that input to this output
```
dist/html/index.html
dist/html/stuff.html
```

I was hoping that there would be a callback that allowed me to express this mapping (like how there is a callback `extractor` for obtaining the [page title](https://codedoc.cc/docs/config/page#page-title)).

**Comment by loreanvictor** [comment]
Yes the generated HTML files maintain the same relative paths as their source markdown files, which allows for easily referencing markdown files from each other, mapping html files back to their sources, etc.

**Comment by bender2k14** [comment]
Ok, I will abandon this then.  I don't want to go against the grain too much.
