### ISSUE TITLE
Auto-reload local preview when assets change

### ISSUE THREAD

**Issue by bender2k14** [CONNECT-platform/codedoc#43]
I edited an image (by cropping it) and then saved it while `codedoc serve` was running, but a rebuild was not triggered.

**Comment by loreanvictor** [comment]
Editing images should not trigger rebuilds. Rebuilds are for updating generated HTML/JS/CSS files, none of which are affected by contents of an image.

However I suspect it would be nice for the dev server to issue a reload to client when assets folder changes. Editing issue title to reflect that.

**Comment by loreanvictor** [comment]
deployed via `0.2.9`.

it is notable that because of this, **CODEDOC** issues a reload to the client for ANY change in assets folder (excluding `.html` files). these reloads are of course not issued if a rebuild process is already ongoing, and as per my limited testing this seems to be working fine. however in different environments / configurations this might need further tweaking.
