### ISSUE TITLE
Allow attribute-value pairs to be delimited by newlines

### ISSUE THREAD

**Issue by bender2k14** [CONNECT-platform/codedoc#44]
[Attributes and their values](https://codedoc.cc/docs/markdown/overview#quoted-components) can appear on the same line separated by a comma.  They can also appear on separate lines but the [commas are still required](https://connect-platform.github.io/coding-blog-plugin/author#author-information).

I like how F# handles this.  For example, consider the [two ways to define a record type](https://connect-platform.github.io/coding-blog-plugin/author#author-information).  If a multiple field-type pairs are on the same line, they must be separated by a semicolon, but when they are on separate lines, then also separating them with a semicolon is optional.

The problem with these commas in the presence of new lines is that they are redundant: [they are not DRY](https://blog.ploeh.dk/2020/05/04/significant-whitespace-is-dry/).

**Comment by loreanvictor** [comment]
> They can also appear on separate lines but the commas are still required.

They cannot really. They _seem_ like they can, simply due to the way new lines work in markdown. The following is one line basically:

```md
hellow
world
```

([commonmark demo](https://spec.commonmark.org/dingus/?text=hellow%0Aworld))

This one is two lines:

```md
hellow

world
```

([commonmark demo](https://spec.commonmark.org/dingus/?text=hellow%0A%0Aworld))

I suspect we could treat `\n` as `,` (I am not sure about encoding here though), however that would be inconsistent with how new lines work in a markdown file.
