### ISSUE TITLE
Code feature to indicate that something doesn't compile

### ISSUE THREAD

**Issue by bender2k14** [CONNECT-platform/codedoc#49]
What about adding support in code blocks to underline specific code with a red squiggle to communicate to the reader that this code doesn't compile?

![2020-07-14_11-22-06_175_devenv](https://user-images.githubusercontent.com/34664007/87450745-868ef880-c5c4-11ea-94b7-d2be82aceeb3.png)

**Comment by loreanvictor** [comment]
that's a pretty nice idea! it is easy to mark a particular line without being intrusive and maintain an acceptable degree of inter-operability, but I suspect marking a particular part of a line would be a bit tougher to get in an intuitive manner.

**Comment by bender2k14** [comment]
Yes, I noticed that the highlighting feature uses syntax that must begin the line.

Accepting that as a constraint, what about some syntax that uses indices to specify which parts should be underlined?

So, maybe the second line in my image could be written as...
```
/*Red(30, 11)*/  new Dictionary<int, int>().TryGetValue(0);
```

...where the first argument is the (1-based) index of the first character the underline (starting after `*/`) in with a red squiggle and the second argument is the number of characters to underline.

**Comment by loreanvictor** [comment]
It has the bonus that the indices can be optional, so people can conveniently mark the whole line but would have to go a step further to properly highlight particular parts of the line. However overall, the process of marking part of the code is not really convenient. Once put in place, such a decision can't be easily rolled back either (since people might have used it on their sites), which means if we find a better solution down the road, we would have to maintain multiple options (at least for a set deprecation period), which is not ideal.

Anyways the way I see it there two options here:
- indicating the boundary of the error at the beginning of the line,
- indicating the boundary of the error within the line,

The first would inevitably lead to a solution such as the one you suggested, the second would mean parsing comment tracks and somewhat highlighting everything in the middle (which is ok since it is done on during pre-rendering). It would look something like this:

```
new Dictionary<int, int>()/*~*/.TryGetValue(0)/*~*/;
```

and would only work for languages which do support in-line comments.

**Comment by bender2k14** [comment]
As an author, I would prefer the within-line syntax, but I don't know what the best API would be.

**Comment by loreanvictor** [comment]
As I am toying with it, actually it is not that intrusive. I suspect I can get the `/*~*/` syntax working for the next update (which should be rolling out tomorrow, but man I've gone slow on CODEDOC updates due to other projects).

**Comment by loreanvictor** [comment]
https://github.com/CONNECT-platform/codedoc/commit/3f64212de080fe0b013e6cd7c7a612da0421c1db

p.s. not released yet.

**Comment by bender2k14** [comment]
Ah, adding both error and warning cases is a good idea.

**Comment by loreanvictor** [comment]
[docs added](https://codedoc.cc/docs/code/highlights#errorwarning-underline), deployed via `0.2.9`

**Comment by bender2k14** [comment]
Does the [code documentation](https://codedoc.cc/docs/code/overview) mention this feature?

**Comment by loreanvictor** [comment]
> Does the [code documentation](https://codedoc.cc/docs/code/overview) mention this feature?

its just showcased on that page, [expanded upon here](https://codedoc.cc/docs/code/highlights#errorwarning-underline).
