### ISSUE TITLE
[Question] Load & use prism plugins for code blocks

### ISSUE THREAD

**Issue by Fictitious-Rotor** [CONNECT-platform/codedoc#56]
Pardon my ignorance, but could you please explain how to load & use prism plugins - such as `command-line` while using codedoc?

Looking through the npm modules I can see that these plugins are present, but loading them through the `script` tag using a relative path is disallowed by my web browser (FF).

Is there a native way to load & use these plugins other than copy pasting the prism plugin into a codedoc plugin and loading them that way?

Many thanks

**Comment by loreanvictor** [comment]
quite honestly I'm not 100% sure. but I can offer some hints (until I can have a deeper look into it later):

- you don't need to load the plugin code via `<script/>` tags. that might have been helpful (depending on the situation) if
highlighting was conducted on the client-side (since you are basically loading highlighter code on the client side). **CODEDOC**, on the other hand, conducts highlighting during the build stage and NOT on the client, for performance.

- **CODEDOC** uses `highlight()` function from Prism to do build-time highlighting, and I cannot find in the documentation how to add plugin functionality to that (not at least with a quick look at [this](https://prismjs.com/plugins/command-line/)). So I would try to find the answer to that question.

based on the answer of that question, you might find a solution, however my guess is that most probably it would require some changes to **CODEDOC**'s `Code` component to make this easy and convenient.

**Comment by loreanvictor** [comment]
ok according to [this issue](https://github.com/PrismJS/prism/issues/1171), using plugins at build time doesn't seem really possible, or at least supported by Prism.
