### ISSUE TITLE
Hyperlink URLs in error messages displayed in the browser

### ISSUE THREAD

**Issue by bender2k14** [CONNECT-platform/codedoc#59]
Quoting https://github.com/CONNECT-platform/codedoc/issues/48#issuecomment-659454760
> ...should display nice errors on the page when there is an error during build.

An exceedingly beautiful error message.  For reference, it looks like this.

![2020-07-27_14-23-41_201_chrome](https://user-images.githubusercontent.com/34664007/88582849-f665a000-d014-11ea-8e78-7c076936fef4.png)

Now that you included it in the browser, I can think of another improvement.

Can the text...
> https://prismjs.com/#supported-languages

...be "upgraded" to a hyperlink?

**Comment by loreanvictor** [comment]
yes it can, great idea!

p.s. why aren't you getting colors on these messages? this has nothing to do with your console anymore, the error string is generated within node and then colored on the client using [ansi_up](https://github.com/drudru/ansi_up). the end result should look like this:

<img width="854" alt="Screen Shot 2020-07-27 at 9 58 08 PM" src="https://user-images.githubusercontent.com/13572283/88586540-d35ae080-d054-11ea-8acc-a7243c94b837.png">

**Comment by bender2k14** [comment]
> why aren't you getting colors on these messages?

*shakes head*...maybe my computer is just color blind 😛 

No colors in Edge either.

> this has nothing to do with your console anymore, the error string is generated within node and then colored on the client using [ansi_up](https://github.com/drudru/ansi_up).

I tried to verify that by running the server in the default Windows command prompt.  As seen before, I can execute `codedoc` but I didn't realize until now that I can't build...for what seems to be an issue related to `node` even though it is in the path.

How do I fix this?

![2020-07-27_15-49-23_203_cmd](https://user-images.githubusercontent.com/34664007/88591214-9b867580-d021-11ea-9b60-7b72166d661c.png)

**Comment by loreanvictor** [comment]
Thats pretty strange. unfortunately I do not have a windows laptop around to be able to test soon, but the issue seems to be with [this line](https://github.com/CONNECT-platform/codedoc-cli/blob/4cfc33e6554caf69f35af7a4900a44180b262f9a/src/build.js#L17) and in turn [these lines](https://github.com/CONNECT-platform/codedoc-cli/blob/4cfc33e6554caf69f35af7a4900a44180b262f9a/src/exec.js#L7-L14). Basically, `ts-node` and `ts-node-dev` are not installed as global packages (unlike `codedoc-cli`), but they are just installed as dependencies of `codedoc-cli`. This means their binaries should be somewhere around `<where-codedoc-cli-is>/node_modules/.bin/`, and the `exec()` function is supposed to run given commands (such as `ts-node` or `ts-node-dev`) in an environment with a modified PATH variable including that address.

**Comment by loreanvictor** [comment]
p.s. not deployed yet. planned to be deployed via `0.2.11`

**Comment by loreanvictor** [comment]
deployed (via `0.2.11`).

**Comment by bender2k14** [comment]
The links work great.

My colors still don't work, and probably because of that, I find the link hard to read and even look at.

![2020-08-14_20-48-00_249_chrome](https://user-images.githubusercontent.com/34664007/90303206-bd7d5600-de71-11ea-8230-f26999551d50.png)

Can you share a screenshot of what it should look like with the correct colors?

**Comment by loreanvictor** [comment]
No thats not related to the console colors missing (which is still exceedingly baffling). It is a primary color that doesn't work well with the dialog background, I should actually enforce the color of the links on these overlays I suspect for maximizing readability (instead of allowing it to be picked up from the theme).

**Comment by loreanvictor** [comment]
fixes deployed via `0.2.12`
