### ISSUE TITLE
custom component iframe width

### ISSUE THREAD

**Issue by nakednous** [CONNECT-platform/codedoc#87]
I'm writing a [component](https://github.com/objetos/p5.quadrille.js/tree/pages/.codedoc/components/p5) to load [p5.js](https://p5js.org/) sketches. For this to work, the p5 `sketch` and its dependencies are loaded within an `iframe` using the `srcdoc` attribute. I'm aiming at setting the `iframe` `width` and `height` attributes from component props. However the width is not being set (not prob with the height), e.g., `> :P5 sketch=/docs/sketches/board.js, width=200, height=400` produces [this](https://objetos.github.io/p5.quadrille.js/#examples) (source is [here](https://github.com/objetos/p5.quadrille.js/blob/pages/docs/md/index.md#examples)). I got the feeling it has to do with the component styling, but I'm totally a newbie in css.

**Comment by loreanvictor** [comment]
there are multiple issues at play here:

- **CODEDOC** itself provides a default styling of `width: 100%` for iframes
- you are providing a `width: 100%` for your particular iframe (class `center`) [here](https://github.com/objetos/p5.quadrille.js/blob/d20e4748eb272c8fe068b5ce3f3d437d7ea9a685/.codedoc/components/p5/style.ts#L21-L26) (and also increasing its width with additional padding)
- generally css styles seem to override properties (if you check dev console and see priority of styles applied, the attribute styles are amongst the last).

I think the easiest solution would be to change [this line](https://github.com/objetos/p5.quadrille.js/blob/d20e4748eb272c8fe068b5ce3f3d437d7ea9a685/.codedoc/components/p5/index.tsx#L34):

```tsx
<iframe
  id={`${name}`} class={`${classes.p5} center`} width={`${w}`} height={`${h}`}
/>
```

and use `style` instead of `width` and `height`, i.e.

```tsx
<iframe
  id={`${name}`} class={`${classes.p5} center`} style={`width: ${w}px, height: ${h}px`}
/>
```

as element styles override all class styles (you would still get some additional width and height due to the paddings and borders, so in this case for example you would get `226x426` with this correction).

**Comment by nakednous** [comment]
Tried your tip, but got a fixed width (spanning all space) and height (that seems different than the 'default'), no matter whether the `center` class is applied or not.

**Comment by loreanvictor** [comment]
can you inspect element, and attach a screenshot of the console (inspecting styles of the iframe, alongside html code of the iframe)? alternatively you could push the code which would allow me to inspect myself and be more able to provide help.

**Comment by loreanvictor** [comment]
@nakednous thanks, I had a typo in my original suggestion. Instead of `,` in the style attribute, it should be `;`, i.e.:

```tsx
<iframe
  id={`${name}`} class={`${classes.p5} center`} style={`width: ${w}px; height: ${h}px`}
/>
```

**Comment by nakednous** [comment]
It's working now. Thanks!
